# Generated by Django 4.0.5 on 2022-08-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
