# Generated by Django 4.0.5 on 2022-08-19 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_remove_book_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOutDate', models.DateField(auto_now_add=True, null=True)),
                ('returnedDate', models.DateField(blank=True, null=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
